// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArm79aPYXd2OjndqLZFnp8erTF9kdoti4',
    appId: '1:770181041411:android:9cd5d56da1ae79911fad36',
    messagingSenderId: '770181041411',
    projectId: 'piyasa-ekrani-5f778',
    storageBucket: 'piyasa-ekrani-5f778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClHNK7Yfzl54gLO_c_7mAMWqDu2y8S5Qo',
    appId: '1:770181041411:ios:3631d5505854fd1c1fad36',
    messagingSenderId: '770181041411',
    projectId: 'piyasa-ekrani-5f778',
    storageBucket: 'piyasa-ekrani-5f778.appspot.com',
    iosClientId: '770181041411-t81gk4abqtacohu893a2ojs087aam174.apps.googleusercontent.com',
    iosBundleId: 'org.piyasaekrani.app.piyasaekrani',
  );
}
