// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNfh-vt9e_FUDKGHNOwXeEwdLShg-PEkE',
    appId: '1:369242570986:android:8f210d9a8521b806c79793',
    messagingSenderId: '369242570986',
    projectId: 'tabldot',
    storageBucket: 'tabldot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI-d3OMAsDpVVYTyAHr3JDf-wJFcDeK1o',
    appId: '1:369242570986:ios:53fb87cde583f964c79793',
    messagingSenderId: '369242570986',
    projectId: 'tabldot',
    storageBucket: 'tabldot.appspot.com',
    iosClientId: '369242570986-am27456e89askogvealrlaggdj06vjgd.apps.googleusercontent.com',
    iosBundleId: 'org.piyasaekrani.app.tabldot',
  );
}
